name: habo
description: Minimalistic habit tracker.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.1.0+1

environment:
  sdk: ">=2.18.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  table_calendar: ^3.2.0
  awesome_dialog: ^3.1.0
  loader_overlay: ^5.0.0
  introduction_screen: ^3.1.11
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.12
  package_info_plus: ^8.3.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  path: ^1.8.3
  fl_chart: ^1.0.0
  just_audio: ^0.10.4
  just_audio_mpv: ^0.1.7
  flutter_file_dialog: ^3.0.2
  file_picker: ^10.2.0
  path_provider: ^2.1.0
  awesome_notifications: ^0.10.1
  timezone: ^0.10.1
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.14.4
  window_manager: ^0.3.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  intl_utils: ^2.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# For now mipmaps are used.
flutter_icons:
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/ios_icon.jpg"
  adaptive_icon_foreground: "assets/images/android_foreground.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21
  android: true
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/images/macos_icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboard/
    - assets/sounds/
    - assets/google_fonts/

flutter_intl:
  enabled: true
